### ISSUE TITLE
Webview implementation Issue

### ISSUE THREAD

**Issue by cyberboysumanjay** [jpillora/cookieauth#1]
It's showing **unauthorised** when I tried to implement Cookieauth in Android webview.
Can you tell me the basic thing behind Cookie Auth? Is Javascript behind this or Cookies?

**Comment by jpillora** [comment]
It just uses cookies. Sorry I've never used Go with Android.

**Comment by jpillora** [comment]
Let me know if you have any more info and we can reopen
